// One-shot build: write the views to /out (gitignored — generated views are
// outputs, never source). For the live page, see serve.mjs.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createEngine } from './engine.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const engine = await createEngine(root);
const { log, views, structural, ms } = await engine.build();
await engine.close();

const cell = (v) => (v == null ? '—' : Array.isArray(v) ? v.join(', ') : String(v)).replace(/\|/g, '\\|');
const table = (rows) => {
  if (!rows.length) return '_(no rows)_\n';
  const cols = Object.keys(rows[0]);
  return [`| ${cols.join(' | ')} |`, `|${cols.map(() => '---').join('|')}|`,
    ...rows.map((r) => `| ${cols.map((c) => cell(r[c])).join(' | ')} |`)].join('\n') + '\n';
};

let out = `# queries.md, reproduced as SQL\n\nGenerated by \`spikes/queries-test/run.mjs\`. Derived; delete freely.\n\n`;
out += `Loaded ${log.files} files in ${ms.load.toFixed(0)} ms.`;
out += log.unparsedTime.length ? ` **Unparsed story_time (unordered):** ${log.unparsedTime.join('; ')}\n\n` : ' Every scene\'s story_time parsed.\n\n';
for (const e of log.parseErrors) out += `**Parse error** — \`${e.file}\`: ${e.message}\n\n`;
for (const e of log.rejected) out += `**Rejected by the database** — \`${e.file}\`: ${e.message}\n\n`;
for (const v of views)
  out += `## ${v.n}. ${v.name}\n\n*query: ${v.query}* — ${v.rows.length} rows, ${v.ms.toFixed(1)} ms\n\n${v.error ? `**Error:** ${v.error}\n` : table(v.rows)}\n`;
for (const s of structural)
  out += `## ${s.rule} — ${s.statement}\n\nEnforced by ${s.enforcedBy}. ${s.checked} presences checked, ${s.violations.length} violation(s).\n\n${s.violations.length ? table(s.violations) : ''}`;

// ── Render queries.md: authored commentary + generated tables ──
// The source file carries `<!-- view: N -->` markers and no tables (§12). Every
// marker must name a view and every presented view must have a marker, or the
// render fails rather than silently dropping one.
const byN = new Map(views.map((v) => [v.n, v]));
const source = readFileSync(join(root, 'queries.md'), 'utf8').replace(/\r\n/g, '\n');
const used = new Set();
const rendered = source.replace(/<!-- view: (\d+) -->/g, (_, n) => {
  const v = byN.get(Number(n));
  if (!v) throw new Error(`queries.md marks view ${n}, which queries.mjs does not define`);
  used.add(v.n);
  return `${table(v.rows)}\n<sub>generated — view ${n}, \`spikes/queries-test/queries.mjs\`, ${v.rows.length} rows</sub>`;
});
const missing = views.filter((v) => v.n <= 7 && !used.has(v.n)).map((v) => v.n);
if (missing.length) throw new Error(`views with no marker in queries.md: ${missing.join(', ')}`);

mkdirSync(join(root, 'out'), { recursive: true });
writeFileSync(join(root, 'out', 'queries-test.md'), out);
writeFileSync(join(root, 'out', 'queries.md'),
  `<!-- GENERATED from queries.md + the corpus by spikes/queries-test/run.mjs. Do not edit; edit queries.md. -->\n\n${rendered}`);
console.error(`rendered out/queries.md (${used.size} views)`);
console.log(out);
