// Build the derived index in memory from the corpus, run the seven views, and
// write them to /out (gitignored — generated views are outputs, never source).
import { PGlite } from '@electric-sql/pglite';
import { btree_gist } from '@electric-sql/pglite/contrib/btree_gist';
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { load } from './load.mjs';
import { queries } from './queries.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../..');

const t0 = performance.now();
const db = await PGlite.create({ extensions: { btree_gist } });
await db.exec(readFileSync(join(here, 'schema.sql'), 'utf8'));
const log = await load(db, root);
const tLoad = performance.now() - t0;

const cell = (v) => (v == null ? '—' : Array.isArray(v) ? v.join(', ') : String(v)).replace(/\|/g, '\\|');
const table = (rows) => {
  if (!rows.length) return '_(no rows)_\n';
  const cols = Object.keys(rows[0]);
  return [`| ${cols.join(' | ')} |`, `|${cols.map(() => '---').join('|')}|`,
    ...rows.map((r) => `| ${cols.map((c) => cell(r[c])).join(' | ')} |`)].join('\n') + '\n';
};

let out = `# queries.md, reproduced as SQL\n\nGenerated by \`spikes/queries-test/run.mjs\`. Derived; delete freely.\n\n`;
out += `Loaded ${log.files} files in ${tLoad.toFixed(0)} ms.`;
out += log.unparsedTime.length ? ` **Unparsed story_time (unordered):** ${log.unparsedTime.join('; ')}\n\n` : ' Every scene\'s story_time parsed.\n\n';

for (const q of queries) {
  const t = performance.now();
  const { rows } = await db.query(q.sql, q.params ?? ['pillar_01']);
  out += `## ${q.n}. ${q.name}\n\n*query: ${q.query}* — ${rows.length} rows, ${(performance.now() - t).toFixed(1)} ms\n\n${table(rows)}\n`;
}

// ── Structural-tier probe: TIME-2 (bilocation) as a DDL constraint ──
// One entity in two overlapping intervals. Scenes here have one-point starts,
// so give each a one-hour interval and ask Postgres to forbid overlap per entity.
let probe = '## Probe — TIME-2 bilocation as an exclusion constraint\n\n';
try {
  await db.exec(`
    CREATE EXTENSION IF NOT EXISTS btree_gist;
    CREATE TABLE presence (entity text, scene text, span numrange,
      EXCLUDE USING gist (entity WITH =, span WITH &&));
    INSERT INTO presence
      SELECT unnest(characters_present), id, numrange(story_day, story_day + 1.0/24)
      FROM scene WHERE story_day IS NOT NULL;`);
  probe += 'Constraint created; the corpus loaded with **no bilocation**.\n\n';
  try {
    await db.exec(`INSERT INTO presence VALUES ('char_marek', 'test.bilocated', numrange(0, 0.01))`);
    probe += '⚠ A deliberately bilocated row was ACCEPTED — the constraint is not enforcing.\n';
  } catch (e) {
    probe += `A deliberately bilocated row (Marek, during ch07) was **rejected by the database**: \`${e.message}\`\n`;
  }
} catch (e) {
  probe += `Could not create the constraint: \`${e.message}\`\n`;
}
out += probe;

mkdirSync(join(root, 'out'), { recursive: true });
writeFileSync(join(root, 'out', 'queries-test.md'), out);
console.log(out);
